### ISSUE TITLE
Rails 5 request specs login_user method undefined

### ISSUE THREAD

**Issue by margOnline** [Sorcery/sorcery#106] opened 2018-02-03 14:51 UTC
Using `Rails 5.0.6, RSpec 3.7.2, Sorcery 0.11.0`, I get  `undefined method 'login_user'` in my request specs. I've used a workaround based on the response by [chrisdurheim](https://github.com/chrisdurheim) in [NoamB issue 775](https://github.com/NoamB/sorcery/issues/775).

Is there any plan for updating the test helpers for use in Rails 5 request specs?

**Comment by ebihara99999** [comment] 2018-02-03 15:03
Thank you for opening the issue.

The problem is fixed in [this PR](https://github.com/Sorcery/sorcery/pull/57), but for some reasons codacy fails, not merged.
I will try understanding the reason and fix it, though I'm not sure when it is. If you like to use the helper soon, do monkey patch followed by my PR or use Sorcery of my branch opened PR in.

**Comment by margOnline** [comment] 2018-02-03 17:21
Thanks for your response @ebihara99999. I'll follow that pr.

**Comment by ebihara99999** [comment] 2018-02-04 11:36
Don't hesitate to tell me if you have another problem with it.

**Comment by RobBikmansurov** [comment] 2018-02-20 12:54
I also try to test with Rspec 3.7 and Rails 5.1.3, but my first problem is this:
`undefined method `authenticates_with_sorcery!' for #<Class:0x00562646a233f8>`

my app/model/user.rb:
`class User < ApplicationRecord

  authenticates_with_sorcery!

...`

Can you tell me what to do?

**Comment by margOnline** [comment] 2018-02-20 13:38
@RobBikmansurov your problem is not related to this issue. I suggest you post your question somewhere like Stackflow and be sure to provide more information than you have here. You may also want to check [here](https://stackoverflow.com/questions/20859510/undefined-method-authenticates-with-sorcery), [here](https://github.com/Sorcery/sorcery/issues/35) and [here](https://github.com/NoamB/sorcery/issues/643).

**Comment by athix** [comment] 2019-12-19 01:18
Hi @margOnline, is this still relevant? I don't recall any PRs coming through for this particular issue, so I'm assuming it probably still is.

**Comment by athix** [comment] 2020-05-05 21:00
No movement, closing for now.

**Closed by athix** 2020-05-05 21:00 UTC
Labels: Bug, Question
