### ISSUE TITLE
Error: undefined method `login'. 'Rails 5' and 'ruby-grape'.

### ISSUE THREAD

**Issue by IonHubber** [Sorcery/sorcery#47] opened 2017-02-15 18:48 UTC
Hello.
Is it possible use core sorcery's methods ('login' for example) in the 'ruby-grape' API controller with Rails 5 ?
Code example:
`class Users < Grape::API`
`resource :users do`
`      post "login" do`
`        if @current_user = login(params[:email], params[:password])`
`          @current_user`
`        else`
`          error!("Invalid email/password combination", 401)`
`        end`
`      end`
`    end`
`end`
I receive error "undefined method `login'".

Module including 
 `include Sorcery::Controller` 
to the class Users < Grape::API is not success for me. 
Thanks for the answer.

**Comment by Ch4s3** [comment] 2017-03-24 04:00
I honestly have no idea, I've never used grape. Could you give us some more context?

**Comment by salimane** [comment] 2017-03-30 11:31
@Ch4s3 the main idea from OP was that can use login a user outside of a controller context, in a ruby script having access to the app database and the sorcery gem.

I would like that too. Any help would be appreciated.

**Comment by mauricew** [comment] 2017-04-05 00:43
You can use the Authenticate method on your user class and it will return the success or failure, but it won't do any sort of after login events (e.g. Activity Logging).

**Comment by gtd** [comment] 2017-08-26 05:26
Ran into this same problem with Rails proper, `ActionController::API`.  The issue is that [the engine](https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/engine.rb) is only including the module in `ActionController::Base`, which is not what `ActionController::API` inherits from.

However adding this is working so far:

```ruby
include Sorcery::Controller
```

 I'm not familiar with Grape, but I imagine you can do the same thing?

**Comment by athix** [comment] 2019-12-19 00:53
@IonHubber @salimane 

Is this still relevant? We've since updated ActionController::API to include the Sorcery controller, and per @mauricew it sounds like you can call authenticate directly outside of a controller context.

I'll close this out as it's been two years since any movement, but please comment/reopen if this is still a concern.

**Closed by athix** 2019-12-19 00:53 UTC
