### ISSUE TITLE
I have encountered two browsers that have not entered an account password, but have just opened the web page and logged into other people's accounts.

### ISSUE THREAD

**Issue by activeliang** [Sorcery/sorcery#247] opened 2020-06-19 08:28 UTC
Please complete all sections.

### Configuration

- Sorcery Version: `0.14.0`
- Ruby Version: `2.6.5`
- Framework: `ruby on rails`
- Platform: `ubuntu 16.04`

### Expected Behavior

Normal login

### Actual Behavior

I have encountered two browsers that have not entered an account password, but have just opened the web page and logged into other people's accounts.

### Steps to Reproduce

Please list all steps to reproduce the issue.

**Comment by athix** [comment] 2020-06-27 07:39
Please try to reproduce this issue with a minimal application, or provide more specifics on what's happening on your existing application. I can't reproduce this with only the current information.

Something that immediately comes to mind is that perhaps your login controller or session management is doing something very incorrect. I would need something to test against to know for sure though.

**Comment by athix** [comment] 2020-07-04 02:57
Closing for now.

**Closed by athix** 2020-07-04 02:57 UTC
Labels: Invalid
