### ISSUE TITLE
Master version fails with "To use reset_password submodule, you must define a mailer"

### ISSUE THREAD

**Issue by Hirurg103** [Sorcery/sorcery#227] opened 2020-04-13 21:22 UTC
### Configuration

- Sorcery Version: [c30cefa7](https://github.com/Sorcery/sorcery/commit/c30cefa751c364ee20b361eb63a766f782b69e5e)
- Ruby Version: `2.5.1`
- Framework: `Rails`, versions `6.0.2.2`, `5.2.4`
- Platform: `Mac OS Mojave 10.14.6`

### Expected Behavior

No error `To use reset_password submodule, you must define a mailer` in the rails development console

### Actual Behavior

Any operation in the rails development console fails with 

```
validate_mailer_defined': To use reset_password submodule, you must define a mailer (config.reset_password_mailer = YourMailerClass). (ArgumentError)
```

### Steps to Reproduce

There is code snippet that reproduces the issue:

```ruby
# issue_with_sorcery.rb
require "bundler/inline"

gemfile(false) do
  gem 'rails', '6.0.2.2'
  gem 'sorcery', github: 'Sorcery/sorcery', branch: 'master', require: false
  gem 'sqlite3', '1.4.2'
end

require 'rails/all'
require 'sorcery'
module TestApp
  class Application < Rails::Application
    config.load_defaults 6.0
  end
end

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Schema.define do
  create_table "users", force: :cascade do |t|
    t.string "email", null: false
    t.string "name"
  end
end

Rails.application.config.sorcery.submodules = [:reset_password]

class UserMailer < ActionMailer::Base
  def reset_password_email(user)
    mail(to: user.email, subject: 'Welcome') do |f|
      f.html { render plain: "Hi Dear #{user.name}" }
    end
  end
end

Rails.application.config.sorcery.configure do |config|
  config.user_config do |user|
    user.reset_password_mailer = UserMailer
    config.user_class = "User"
  end
end

class User < ActiveRecord::Base
  authenticates_with_sorcery!
end

u = User.create(email: 'jane@example.org', name: 'Jane')
puts u.attributes
```
It is expected that this script will print user attribute values when you run it with `ruby issue_with_sorcery.rb` but it fails with
```
~/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/sorcery-c30cefa751c3/lib/sorcery/model/submodules/reset_password.rb:77:in `validate_mailer_defined': To use reset_password submodule, you must define a mailer (config.reset_password_mailer = YourMailerClass). (ArgumentError)
```

I started seeing this error after I upgraded to the master branch to fix [deprecation warnings in Rails 6](https://github.com/Sorcery/sorcery/pull/209)

**Comment by athix** [comment] 2020-04-13 21:27
@Hirurg103 Looking at that script, it might be failing because as soon as you add the submodule, it's performing the config validation, but you don't update the config until later in the script. Can you try moving the submodule call between the User definition and mailer config?

**Comment by Hirurg103** [comment] 2020-04-14 10:28
Hi @athix ,

> Looking at that script, it might be failing because as soon as you add the submodule, it's performing the config validation, but you don't update the config until later in the script.

I am seeing this issue in a real rails app too.

> Can you try moving the submodule call between the User definition and mailer config?

yea, no problem:
```ruby
# issue_with_sorcery.rb
class UserMailer; end
Rails.application.config.sorcery.submodules = [:reset_password]
Rails.application.config.sorcery.configure do |config|
...
```
With this configuration I see the same error.

As I am aware Rails first loads `config/initializers` files and then files in the `app` directory.
This issue is reproducible in the Rails console in the development environment only. Rails server in the development works with no errors. I tried to add `require 'user'` at the top of the sorcery initializer and it fixed the problem with rails console:

```ruby
require 'user'
Rails.application.config.sorcery.submodules = [:reset_password]
...
```

I guess that this model require from an initializer file is discouraged by rails community - what do you think?

**Comment by athix** [comment] 2020-04-14 10:37
Ah, yeah that's an interesting problem for sure. The easiest thing might
honestly be to ping the Rails guys and see what they think. I don't fully
understand their reason for the zeitwerk autoloading changes, so they might
be able to provide some key insights.

That said, I need to get some sleep for now. I'll add this to my priority
todo list and follow up soon.

>

**Comment by Hirurg103** [comment] 2020-04-14 20:13
@athix , have a good sleep man

I tried to switch to the `:classic` autoloading mode but it didn't help to fix the bug:
```ruby
module TestApp
  class Application < Rails::Application
    config.load_defaults 6.0
    config.autoloader = :classic
  end
end
```

Looks like I spot the issue: when I move user definition above the sorcery config all works OK:
```ruby
class User < ActiveRecord::Base
  authenticates_with_sorcery!
end

Rails.application.config.sorcery.configure do |config|
   ...
end
```

Do sorcery expect the User model to be loaded before the configuration?

**Comment by Hirurg103** [comment] 2020-04-14 21:57
@athix Looks like this error occurs due to load order.

Loading `User` class in the development console causes [`authenticates_with_sorcery!`](https://github.com/Sorcery/sorcery/blob/c30cefa751c364ee20b361eb63a766f782b69e5e/lib/sorcery/model.rb#L10) to be called. I inspected and found out that at this stage [`::Sorcery::Controller::Config.user_config`](https://github.com/Sorcery/sorcery/blob/c30cefa751c364ee20b361eb63a766f782b69e5e/lib/sorcery/model.rb#L20) is nil. This happens because `ActionController::Base` has [not been loaded yet](https://github.com/Sorcery/sorcery/blob/c30cefa751c364ee20b361eb63a766f782b69e5e/lib/sorcery/engine.rb#L16) and thus [`Sorcery :: Controller.included`](https://github.com/Sorcery/sorcery/blob/c30cefa751c364ee20b361eb63a766f782b69e5e/lib/sorcery/controller.rb#L3) has not been called. And thus [`Config.configure!`](https://github.com/Sorcery/sorcery/blob/c30cefa751c364ee20b361eb63a766f782b69e5e/lib/sorcery/controller.rb#L18) has not been called. And therefore the configuration block in the sorcery initializer has not been evaluated.

If I type the rails console `ActionController::Base` and then `User` all works OK.

Is there any reason you save sorcery config block in a variable and then evaluate it when `ActionController::Base` is loaded? Why not set all configuration options when sorcery initializer file evaluates?

**Comment by athix** [comment] 2020-04-14 22:21
@Hirurg103 That's a good question, I don't think the configuration loading block has been touched in years, other than a year or two ago it had to be updated to support the Rails 5 `on_load` method for some reason that I can't recall.

Maybe you can try alternative loading schemes, and see if they solve your issue without breaking functionality? The biggest thing I would be wary of is a load order dependency causing classes to not be configured properly, and what happens if we're trying to define a pointer to a class that hasn't been loaded yet (e.g. when we declare [`config.user_class = "<%= model_class_name %>"`](https://github.com/Sorcery/sorcery/blob/c30cefa751c364ee20b361eb63a766f782b69e5e/lib/generators/sorcery/templates/initializer.rb#L544), will that blow up on the User class not being defined?).

**Comment by Hirurg103** [comment] 2020-04-15 19:29
> Maybe you can try alternative loading schemes, and see if they solve your issue without breaking functionality?

OK, @athix I will try to change the configuration flow to evaluate the config block in the initializer file. Let's see if this works

**Comment by futuretap** [comment] 2020-05-01 12:47
Will this bug eventually be fixed?

**Comment by athix** [comment] 2020-05-01 18:34
@Hirurg103 @futuretap #234 has been merged into master, can you try the latest version and see if it resolves the issues on your end? Testing locally, it appears to have fixed the loading issues, although the error I was receiving was different so it's possible it's still broken.

**Comment by revickulous2001** [comment] 2020-05-25 20:10
I'm having this same issue as well.  This issue persists on version 0.15 too.

**Comment by futuretap** [comment] 2020-05-25 20:16
@athix looks like I didn't answer your question. 0.15 does fix the issue for me, thanks. Don't know why @revickulous2001 still has problems.

**Comment by athix** [comment] 2020-05-25 20:20
@revickulous2001 when are you seeing this error, and what error are you getting exactly?

- When you're running the server?
- When you're running specs?
- Both?
- Some other situation(s)?

**Comment by revickulous2001** [comment] 2020-05-25 20:46
@athix I am getting this error when I try to run reference the User model from the console.

I have loaded sorcery into a new project (less than a day old).  The error occurs when I:

- `rails c` from the command line.
- `User.count`

I'm still looking into things and messing around with settings on my end.  So far, nothing has helped the issue.

As noted by @Hirurg103 earlier, when I type `ActionController::Base` followed by `User` into the console, the error goes away and everything works.

**Comment by athix** [comment] 2020-05-25 20:49
@revickulous2001 can you make sure that you're calling `authenticates_with_sorcery!` in the user model? It sounds like the issue is related to the config file not being loaded in.

**Comment by revickulous2001** [comment] 2020-05-25 20:57
@athix I am calling it.  Here is my user model.

```
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end
```

The project is brand new so I've added no features to it except for TailwindCSS, StimulusJS, Sorcery, and bcrypt.

The Sorcery gem command is currently: `gem 'sorcery', github: 'Sorcery/sorcery', branch: 'master'`, though I've tried a few others.
I'm using ruby 2.6.3 and Rails 6.0.3.

**Comment by athix** [comment] 2020-05-25 21:19
@revickulous2001 can you post your Sorcery config file? *(double check that any sensitive information is removed first, e.g. oauth provider keys/secrets)*

**Comment by revickulous2001** [comment] 2020-05-25 21:23
@athix absolutely.  I'm actually in the middle of completely removing Sorcery and the UserMailer.  I'm going drop and re-create my database, reinstall Sorcery, and see if the issue persists.  If so, I'll upload the config file.  If this fixes it, I'll let you know as well.

**Comment by revickulous2001** [comment] 2020-05-25 22:28
@athix I had some strange issues.  First I deleted app/models/user.rb.  Then I deleted all migration files.  Then I deleted config/initializers/sorcery.rb.  Then I ran `rails db:drop db:create db:migrate`.  When I then attempt to run `rails g sorcery:install`, I get this error:

/Users/michael/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- /Users/michael/projects/my_project/app/models/user.rb (LoadError)
The file /Users/michael/projects/my_project/app/models/user.rb does not appear to exist

The generator isn't creating the user.rb file for some reason.

So I loaded up a completely fresh project with `rails new sorcery_test --database=postgresql`.  I configured my database.  I added `gem "sorcery", "0.15"` to my Gemfile and then ran `bundle install`.  `rails g sorcery:install` works fine on this installation.  So I created my UserMailer class using the Rails generator.

However, when I go to the rails console and execute `User.count`, I get back an error that says `NameError (uninitialized constant UserMailer)`.

Once I run a `reload!` in the console, everything works fine.  Is this a loading issue?

**Comment by revickulous2001** [comment] 2020-05-26 02:32
@athix after further investigation, it doesn't seem like this is a Sorcery issue.

I removed Spring dependencies from my Gemfile, rebundled, and everything is working now.

For some reason, Spring seemed to be interfering with using my User model.  Very odd.  I'm sorry for having wasted your time today, @athix.  But I do appreciate all of your help.

**Comment by athix** [comment] 2020-05-26 02:39
@revickulous2001 no worries! I've actually had similar problems so often that my first step when debugging is running `spring stop`. It likes caching files when it shouldn't, and then no matter how much you change it nothing fixes it because spring still has the wrong code cached...Probably a config thing or something, but never got to fixing it.

Glad you've got it figured out! Seems like the loading issue is solved for now, going to close this issue out.

**Closed by athix** 2020-05-26 02:39 UTC
Labels: Bug

**Comment by wout** [comment] 2020-08-01 18:44
I just ran into this issue too when using the rails console. Simply typing `ActionController::Base` and enter fixes the issue.
